// export const popularDestinations = [
//     {
//       id: 1,
//       name: 'Goa',
//       image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=400&h=300&fit=crop',
//       description: 'Beach paradise with vibrant nightlife',
//       packages: 45,
//     },
//     {
//       id: 2,
//       name: 'Kerala',
//       image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=400&h=300&fit=crop',
//       description: 'Backwaters and serene landscapes',
//       packages: 38,
//     },
//     {
//       id: 3,
//       name: 'Rajasthan',
//       image: 'https://images.unsplash.com/photo-1524307875964-4c93f6f20d12?w-400&h=300&fit=crop',
//       description: 'Royal heritage and desert safaris',
//       packages: 52,
//     },
//     {
//       id: 4,
//       name: 'Himachal Pradesh',
//       image: 'https://images.unsplash.com/photo-1564507004663-b6dfb3e2ede5?w=400&h=300&fit=crop',
//       description: 'Majestic mountains and adventure',
//       packages: 67,
//     },
//     {
//       id: 5,
//       name: 'Andaman',
//       image: 'https://images.unsplash.com/photo-1552465011-b4e30bf7349d?w=400&h=300&fit=crop',
//       description: 'Pristine beaches and water sports',
//       packages: 28,
//     },
//     {
//       id: 6,
//       name: 'Sikkim',
//       image: 'https://images.unsplash.com/photo-1626957566494-4f0b5044452a?w=400&h=300&fit=crop',
//       description: 'Himalayan beauty and monasteries',
//       packages: 31,
//     },
//   ];
  
//   export const tourPackages = [
//     {
//       id: 1,
//       title: 'Goa Beach Bliss',
//       destination: 'Goa',
//       duration: '5 Days / 4 Nights',
//       description: 'Experience the best of Goa beaches, nightlife, and Portuguese heritage',
//       price: 14999,
//       discountPrice: 12999,
//       rating: 4.8,
//       reviews: 234,
//       image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w-600&h=400&fit=crop',
//       tags: ['Beach', 'Nightlife', 'Relax'],
//       inclusions: ['Accommodation', 'Breakfast', 'Sightseeing', 'Transport'],
//     },
//     {
//       id: 2,
//       title: 'Kerala Backwaters',
//       destination: 'Kerala',
//       duration: '7 Days / 6 Nights',
//       description: 'Houseboat stay, tea gardens, and Ayurvedic experiences',
//       price: 24999,
//       discountPrice: 21999,
//       rating: 4.9,
//       reviews: 189,
//       image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w-600&h=400&fit=crop',
//       tags: ['Backwaters', 'Nature', 'Wellness'],
//       inclusions: ['Houseboat', 'Meals', 'Ayurveda', 'Guide'],
//     },
//     {
//       id: 3,
//       title: 'Royal Rajasthan',
//       destination: 'Rajasthan',
//       duration: '8 Days / 7 Nights',
//       description: 'Explore palaces, forts, and desert camps across Rajasthan',
//       price: 32999,
//       discountPrice: 29999,
//       rating: 4.7,
//       reviews: 312,
//       image: 'https://images.unsplash.com/photo-1524307875964-4c93f6f20d12?w-600&h=400&fit=crop',
//       tags: ['Heritage', 'Desert', 'Culture'],
//       inclusions: ['Hotels', 'Meals', 'Camel Safari', 'Entries'],
//     },
//     {
//       id: 4,
//       title: 'Himachal Adventure',
//       destination: 'Himachal',
//       duration: '6 Days / 5 Nights',
//       description: 'Trekking, paragliding, and mountain views in Manali & Kasol',
//       price: 18999,
//       discountPrice: 16999,
//       rating: 4.6,
//       reviews: 156,
//       image: 'https://images.unsplash.com/photo-1564507004663-b6dfb3e2ede5?w-600&h=400&fit=crop',
//       tags: ['Adventure', 'Mountains', 'Trekking'],
//       inclusions: ['Accommodation', 'Activities', 'Meals', 'Guide'],
//     },
//     {
//       id: 5,
//       title: 'Andaman Island Hopping',
//       destination: 'Andaman',
//       duration: '6 Days / 5 Nights',
//       description: 'Scuba diving, island tours, and beach relaxation',
//       price: 27999,
//       discountPrice: 24999,
//       rating: 4.9,
//       reviews: 278,
//       image: 'https://images.unsplash.com/photo-1552465011-b4e30bf7349d?w-600&h=400&fit=crop',
//       tags: ['Island', 'Water Sports', 'Beach'],
//       inclusions: ['Resort Stay', 'Scuba Diving', 'Island Tours', 'Meals'],
//     },
//     {
//       id: 6,
//       title: 'Sikkim Buddha Trail',
//       destination: 'Sikkim',
//       duration: '7 Days / 6 Nights',
//       description: 'Monastery visits, Himalayan views, and cultural immersion',
//       price: 21999,
//       discountPrice: 19999,
//       rating: 4.8,
//       reviews: 145,
//       image: 'https://images.unsplash.com/photo-1626957566494-4f0b5044452a?w-600&h=400&fit=crop',
//       tags: ['Mountains', 'Culture', 'Spiritual'],
//       inclusions: ['Accommodation', 'Transport', 'Guide', 'Permits'],
//     },
//   ];
  
//   export const testimonials = [
//     {
//       id: 1,
//       name: 'Priya Sharma',
//       role: 'Software Engineer',
//       content: 'TripWale made our honeymoon in Goa absolutely magical! Everything was perfectly arranged.',
//       rating: 5,
//       image: 'https://randomuser.me/api/portraits/women/32.jpg',
//     },
//     {
//       id: 2,
//       name: 'Raj Patel',
//       role: 'Business Owner',
//       content: 'The Kerala backwaters tour exceeded our expectations. Professional service throughout.',
//       rating: 5,
//       image: 'https://randomuser.me/api/portraits/men/54.jpg',
//     },
//     {
//       id: 3,
//       name: 'Anjali Mehta',
//       role: 'Doctor',
//       content: 'Family trip to Rajasthan was seamless. Great accommodations and knowledgeable guides.',
//       rating: 4,
//       image: 'https://randomuser.me/api/portraits/women/65.jpg',
//     },
//   ];
  
//   export const whyChooseUs = [
//     {
//       id: 1,
//       title: 'Best Price Guarantee',
//       description: 'We offer the most competitive prices with no hidden charges.',
//       icon: '💰',
//     },
//     {
//       id: 2,
//       title: '24/7 Customer Support',
//       description: 'Our travel experts are available round the clock to assist you.',
//       icon: '📞',
//     },
//     {
//       id: 3,
//       title: 'Customizable Packages',
//       description: 'Tailor-made itineraries to match your preferences and budget.',
//       icon: '🎯',
//     },
//     {
//       id: 4,
//       title: 'Verified Partners',
//       description: 'All our hotels and service providers are carefully vetted.',
//       icon: '✅',
//     },
//   ];

export const popularDestinations = [
    {
      id: 1,
      name: 'Goa',
      image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=400&h=300&fit=crop',
      description: 'Beach paradise with vibrant nightlife',
      packages: 45,
      rating: 4.7,
      tags: ['Beach', 'Nightlife', 'Portuguese'],
      startingPrice: 7999,
    },
    {
      id: 2,
      name: 'Kerala',
      image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=400&h=300&fit=crop',
      description: 'Backwaters and serene landscapes',
      packages: 38,
      rating: 4.9,
      tags: ['Backwaters', 'Nature', 'Ayurveda'],
      startingPrice: 12999,
    },
    {
      id: 3,
      name: 'Rajasthan',
      image: 'https://images.unsplash.com/photo-1524307875964-4c93f6f20d12?w=400&h=300&fit=crop',
      description: 'Royal heritage and desert safaris',
      packages: 52,
      rating: 4.6,
      tags: ['Heritage', 'Desert', 'Culture'],
      startingPrice: 14999,
    },
    {
      id: 4,
      name: 'Himachal Pradesh',
      image: 'https://images.unsplash.com/photo-1564507004663-b6dfb3e2ede5?w=400&h=300&fit=crop',
      description: 'Majestic mountains and adventure',
      packages: 67,
      rating: 4.8,
      tags: ['Mountains', 'Adventure', 'Trekking'],
      startingPrice: 8999,
    },
    {
      id: 5,
      name: 'Andaman',
      image: 'https://images.unsplash.com/photo-1552465011-b4e30bf7349d?w=400&h=300&fit=crop',
      description: 'Pristine beaches and water sports',
      packages: 28,
      rating: 4.9,
      tags: ['Island', 'Beach', 'Scuba'],
      startingPrice: 18999,
    },
    {
      id: 6,
      name: 'Sikkim',
      image: 'https://images.unsplash.com/photo-1626957566494-4f0b5044452a?w=400&h=300&fit=crop',
      description: 'Himalayan beauty and monasteries',
      packages: 31,
      rating: 4.7,
      tags: ['Mountains', 'Culture', 'Monasteries'],
      startingPrice: 11999,
    },
  ];
  
  export const tourPackages = [
    {
      id: 1,
      title: 'Goa Beach Bliss',
      destination: 'Goa',
      duration: '5 Days / 4 Nights',
      description: 'Experience the best of Goa beaches, nightlife, and Portuguese heritage',
      price: 14999,
      discountPrice: 12999,
      rating: 4.8,
      reviews: 234,
      image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&h=400&fit=crop',
      tags: ['Beach', 'Nightlife', 'Relax'],
      inclusions: ['Accommodation', 'Breakfast', 'Sightseeing', 'Transport'],
      groupSize: '2-12 People',
      difficulty: 'Easy',
      bestSeason: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
      highlights: [
        'North Goa Beaches',
        'Portuguese Heritage Walk',
        'Dudhsagar Falls',
        'Cruise Party',
        'Local Seafood Experience',
      ],
    },
    {
      id: 2,
      title: 'Kerala Backwaters',
      destination: 'Kerala',
      duration: '7 Days / 6 Nights',
      description: 'Houseboat stay, tea gardens, and Ayurvedic experiences',
      price: 24999,
      discountPrice: 21999,
      rating: 4.9,
      reviews: 189,
      image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=600&h=400&fit=crop',
      tags: ['Backwaters', 'Nature', 'Wellness'],
      inclusions: ['Houseboat', 'Meals', 'Ayurveda', 'Guide'],
      groupSize: '2-8 People',
      difficulty: 'Easy',
      bestSeason: ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb'],
      highlights: [
        'Alleppey Houseboat Stay',
        'Munnar Tea Gardens',
        'Thekkady Wildlife',
        'Ayurvedic Treatment',
        'Kathakali Performance',
      ],
    },
    {
      id: 3,
      title: 'Royal Rajasthan',
      destination: 'Rajasthan',
      duration: '8 Days / 7 Nights',
      description: 'Explore palaces, forts, and desert camps across Rajasthan',
      price: 32999,
      discountPrice: 29999,
      rating: 4.7,
      reviews: 312,
      image: 'https://images.unsplash.com/photo-1524307875964-4c93f6f20d12?w=600&h=400&fit=crop',
      tags: ['Heritage', 'Desert', 'Culture'],
      inclusions: ['Hotels', 'Meals', 'Camel Safari', 'Entries'],
      groupSize: '2-15 People',
      difficulty: 'Moderate',
      bestSeason: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
      highlights: [
        'Jaipur City Palace',
        'Jodhpur Mehrangarh Fort',
        'Udaipur Lake Palace',
        'Jaisalmer Desert Camp',
        'Pushkar Camel Fair',
      ],
    },
    {
      id: 4,
      title: 'Himachal Adventure',
      destination: 'Himachal',
      duration: '6 Days / 5 Nights',
      description: 'Trekking, paragliding, and mountain views in Manali & Kasol',
      price: 18999,
      discountPrice: 16999,
      rating: 4.6,
      reviews: 156,
      image: 'https://images.unsplash.com/photo-1564507004663-b6dfb3e2ede5?w=600&h=400&fit=crop',
      tags: ['Adventure', 'Mountains', 'Trekking'],
      inclusions: ['Accommodation', 'Activities', 'Meals', 'Guide'],
      groupSize: '2-10 People',
      difficulty: 'Moderate',
      bestSeason: ['Mar', 'Apr', 'May', 'Sep', 'Oct', 'Nov'],
      highlights: [
        'Manali Solang Valley',
        'Kasol Riverside Camping',
        'Paragliding in Bir Billing',
        'Great Himalayan National Park',
        'Hot Water Springs',
      ],
    },
    {
      id: 5,
      title: 'Andaman Island Hopping',
      destination: 'Andaman',
      duration: '6 Days / 5 Nights',
      description: 'Scuba diving, island tours, and beach relaxation',
      price: 27999,
      discountPrice: 24999,
      rating: 4.9,
      reviews: 278,
      image: 'https://images.unsplash.com/photo-1552465011-b4e30bf7349d?w=600&h=400&fit=crop',
      tags: ['Island', 'Water Sports', 'Beach'],
      inclusions: ['Resort Stay', 'Scuba Diving', 'Island Tours', 'Meals'],
      groupSize: '2-8 People',
      difficulty: 'Easy',
      bestSeason: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr'],
      highlights: [
        'Havelock Island',
        'Scuba Diving Certification',
        'Cellular Jail Light Show',
        'Radhanagar Beach Sunset',
        'Glass Bottom Boat Ride',
      ],
    },
    {
      id: 6,
      title: 'Sikkim Buddha Trail',
      destination: 'Sikkim',
      duration: '7 Days / 6 Nights',
      description: 'Monastery visits, Himalayan views, and cultural immersion',
      price: 21999,
      discountPrice: 19999,
      rating: 4.8,
      reviews: 145,
      image: 'https://images.unsplash.com/photo-1626957566494-4f0b5044452a?w=600&h=400&fit=crop',
      tags: ['Mountains', 'Culture', 'Spiritual'],
      inclusions: ['Accommodation', 'Transport', 'Guide', 'Permits'],
      groupSize: '2-12 People',
      difficulty: 'Moderate',
      bestSeason: ['Mar', 'Apr', 'May', 'Sep', 'Oct', 'Nov'],
      highlights: [
        'Gangtok Ropeway',
        'Tsomgo Lake',
        'Rumtek Monastery',
        'Nathula Pass',
        'Local Cuisine Tour',
      ],
    },
    {
      id: 7,
      title: 'Uttarakhand Spiritual',
      destination: 'Uttarakhand',
      duration: '5 Days / 4 Nights',
      description: 'Temple visits, river rafting, and hill station exploration',
      price: 15999,
      discountPrice: 13999,
      rating: 4.5,
      reviews: 98,
      image: 'https://images.unsplash.com/photo-1564507004663-b6dfb3e2ede5?w=600&h=400&fit=crop',
      tags: ['Spiritual', 'Mountains', 'Adventure'],
      inclusions: ['Hotel Stay', 'Breakfast', 'Sightseeing', 'Activities'],
      groupSize: '2-15 People',
      difficulty: 'Easy',
      bestSeason: ['Year Round'],
      highlights: [
        'Rishikesh Ganga Aarti',
        'River Rafting',
        'Haridwar Temples',
        'Mussoorie Mall Road',
        'Yoga and Meditation',
      ],
    },
    {
      id: 8,
      title: 'Ladakh Motorcycle Tour',
      destination: 'Ladakh',
      duration: '10 Days / 9 Nights',
      description: 'Epic motorcycle journey through high mountain passes',
      price: 45999,
      discountPrice: 41999,
      rating: 4.9,
      reviews: 167,
      image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop',
      tags: ['Adventure', 'Motorcycle', 'Mountains'],
      inclusions: ['Royal Enfield Bike', 'Fuel', 'Accommodation', 'Guide'],
      groupSize: '4-8 People',
      difficulty: 'Challenging',
      bestSeason: ['Jun', 'Jul', 'Aug', 'Sep'],
      highlights: [
        'Leh Palace',
        'Khardung La Pass',
        'Pangong Lake',
        'Nubra Valley',
        'Magnetic Hill',
      ],
    },
  ];
  
  export const testimonials = [
    {
      id: 1,
      name: 'Priya Sharma',
      role: 'Software Engineer',
      content: 'TripWale made our honeymoon in Goa absolutely magical! Everything was perfectly arranged.',
      rating: 5,
      image: 'https://randomuser.me/api/portraits/women/32.jpg',
      date: '2024-01-15',
      tour: 'Goa Beach Bliss',
    },
    {
      id: 2,
      name: 'Raj Patel',
      role: 'Business Owner',
      content: 'The Kerala backwaters tour exceeded our expectations. Professional service throughout.',
      rating: 5,
      image: 'https://randomuser.me/api/portraits/men/54.jpg',
      date: '2024-02-20',
      tour: 'Kerala Backwaters',
    },
    {
      id: 3,
      name: 'Anjali Mehta',
      role: 'Doctor',
      content: 'Family trip to Rajasthan was seamless. Great accommodations and knowledgeable guides.',
      rating: 4,
      image: 'https://randomuser.me/api/portraits/women/65.jpg',
      date: '2024-03-10',
      tour: 'Royal Rajasthan',
    },
    {
      id: 4,
      name: 'Vikram Singh',
      role: 'College Student',
      content: 'Ladakh bike trip was the adventure of a lifetime! Well-organized and safe.',
      rating: 5,
      image: 'https://randomuser.me/api/portraits/men/22.jpg',
      date: '2023-09-05',
      tour: 'Ladakh Motorcycle Tour',
    },
    {
      id: 5,
      name: 'Neha Kapoor',
      role: 'Marketing Manager',
      content: 'Andaman scuba diving experience was incredible. Highly recommended!',
      rating: 5,
      image: 'https://randomuser.me/api/portraits/women/44.jpg',
      date: '2024-01-28',
      tour: 'Andaman Island Hopping',
    },
  ];
  
  export const whyChooseUs = [
    {
      id: 1,
      title: 'Best Price Guarantee',
      description: 'We offer the most competitive prices with no hidden charges.',
      icon: '💰',
      details: 'If you find a lower price within 24 hours, we will match it.',
    },
    {
      id: 2,
      title: '24/7 Customer Support',
      description: 'Our travel experts are available round the clock to assist you.',
      icon: '📞',
      details: 'Call, chat, or email - we respond within 15 minutes.',
    },
    {
      id: 3,
      title: 'Customizable Packages',
      description: 'Tailor-made itineraries to match your preferences and budget.',
      icon: '🎯',
      details: 'Choose hotels, activities, and duration as per your choice.',
    },
    {
      id: 4,
      title: 'Verified Partners',
      description: 'All our hotels and service providers are carefully vetted.',
      icon: '✅',
      details: 'Regular quality checks and customer feedback analysis.',
    },
    {
      id: 5,
      title: 'Secure Payments',
      description: 'Your payments are protected with advanced security.',
      icon: '🔒',
      details: 'SSL encryption and multiple payment options.',
    },
    {
      id: 6,
      title: 'Flexible Cancellation',
      description: 'Easy cancellation and rescheduling options.',
      icon: '🔄',
      details: 'Cancel up to 7 days before travel for full refund.',
    },
  ];
  
  export const teamMembers = [
    {
      id: 1,
      name: 'Aarav Sharma',
      role: 'Founder & CEO',
      experience: '15+ years in tourism',
      bio: 'Passionate about creating memorable travel experiences.',
      image: 'https://randomuser.me/api/portraits/men/51.jpg',
    },
    {
      id: 2,
      name: 'Neha Patel',
      role: 'Travel Director',
      experience: '12+ years experience',
      bio: 'Expert in curating personalized travel itineraries.',
      image: 'https://randomuser.me/api/portraits/women/33.jpg',
    },
    {
      id: 3,
      name: 'Rohan Singh',
      role: 'Operations Head',
      experience: '10+ years in logistics',
      bio: 'Ensures smooth execution of all travel plans.',
      image: 'https://randomuser.me/api/portraits/men/32.jpg',
    },
    {
      id: 4,
      name: 'Priya Desai',
      role: 'Customer Success',
      experience: '8+ years in hospitality',
      bio: 'Dedicated to customer satisfaction and support.',
      image: 'https://randomuser.me/api/portraits/women/44.jpg',
    },
  ];
  
  export const faqs = [
    {
      id: 1,
      question: 'How do I book a tour package?',
      answer: 'You can book directly through our website by selecting your preferred package, choosing dates, and completing the payment.',
    },
    {
      id: 2,
      question: 'What is included in the tour price?',
      answer: 'Inclusions vary by package but typically include accommodation, some meals, transport, and guided tours. Check package details for specifics.',
    },
    {
      id: 3,
      question: 'Can I customize my tour package?',
      answer: 'Yes, we offer customizable packages. Contact our travel experts who will help modify any package as per your requirements.',
    },
    {
      id: 4,
      question: 'What is your cancellation policy?',
      answer: 'We offer free cancellation up to 7 days before travel. Within 7 days, cancellation charges may apply based on hotel/airline policies.',
    },
    {
      id: 5,
      question: 'Do I need travel insurance?',
      answer: 'We highly recommend travel insurance. We can assist you in getting comprehensive coverage for your trip.',
    },
    {
      id: 6,
      question: 'How do I make payments?',
      answer: 'We accept all major credit/debit cards, UPI, net banking, and wallets. EMI options are also available.',
    },
  ];
  
  export const blogPosts = [
    {
      id: 1,
      title: '10 Must-Visit Places in Goa',
      excerpt: 'Discover the hidden gems and popular spots in India\'s favorite beach destination.',
      image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&h=400&fit=crop',
      date: '2024-03-15',
      category: 'Destinations',
    },
    {
      id: 2,
      title: 'Monsoon Travel: Best Places in India',
      excerpt: 'Experience the magic of monsoon at these beautiful destinations.',
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&h=400&fit=crop',
      date: '2024-06-20',
      category: 'Seasons',
    },
    {
      id: 3,
      title: 'Travel Hacks for Budget Trips',
      excerpt: 'Smart tips to make your travel more affordable without compromising on experience.',
      image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop',
      date: '2024-02-10',
      category: 'Tips',
    },
  ];
  
  export const offerBanners = [
    {
      id: 1,
      title: 'Early Bird Special',
      description: 'Book 60 days in advance and get 20% off',
      code: 'EARLY20',
      validUntil: '2024-12-31',
    },
    {
      id: 2,
      title: 'Family Package',
      description: 'Get 15% off on family bookings (4+ members)',
      code: 'FAMILY15',
      validUntil: '2024-12-31',
    },
    {
      id: 3,
      title: 'Honeymoon Package',
      description: 'Special romantic packages with complimentary upgrades',
      code: 'HONEYMOON',
      validUntil: '2024-12-31',
    },
  ];